/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as PublicRouteImport } from './routes/_public/route';
import { Route as PublicIndexImport } from './routes/_public/index';
import { Route as PublicAboutImport } from './routes/_public/about';
import { Route as PublicPokemonRouteImport } from './routes/_public/pokemon/route';
import { Route as PublicPokemonIndexImport } from './routes/_public/pokemon/index';
import { Route as PublicPokemonPokemonIDImport } from './routes/_public/pokemon/$pokemonID';

// Create/Update Routes

const PublicRouteRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any);

const PublicIndexRoute = PublicIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any);

const PublicAboutRoute = PublicAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any);

const PublicPokemonRouteRoute = PublicPokemonRouteImport.update({
  id: '/pokemon',
  path: '/pokemon',
  getParentRoute: () => PublicRouteRoute,
} as any);

const PublicPokemonIndexRoute = PublicPokemonIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicPokemonRouteRoute,
} as any);

const PublicPokemonPokemonIDRoute = PublicPokemonPokemonIDImport.update({
  id: '/$pokemonID',
  path: '/$pokemonID',
  getParentRoute: () => PublicPokemonRouteRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof PublicRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/_public/pokemon': {
      id: '/_public/pokemon';
      path: '/pokemon';
      fullPath: '/pokemon';
      preLoaderRoute: typeof PublicPokemonRouteImport;
      parentRoute: typeof PublicRouteImport;
    };
    '/_public/about': {
      id: '/_public/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof PublicAboutImport;
      parentRoute: typeof PublicRouteImport;
    };
    '/_public/': {
      id: '/_public/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PublicIndexImport;
      parentRoute: typeof PublicRouteImport;
    };
    '/_public/pokemon/$pokemonID': {
      id: '/_public/pokemon/$pokemonID';
      path: '/$pokemonID';
      fullPath: '/pokemon/$pokemonID';
      preLoaderRoute: typeof PublicPokemonPokemonIDImport;
      parentRoute: typeof PublicPokemonRouteImport;
    };
    '/_public/pokemon/': {
      id: '/_public/pokemon/';
      path: '/';
      fullPath: '/pokemon/';
      preLoaderRoute: typeof PublicPokemonIndexImport;
      parentRoute: typeof PublicPokemonRouteImport;
    };
  }
}

// Create and export the route tree

interface PublicPokemonRouteRouteChildren {
  PublicPokemonPokemonIDRoute: typeof PublicPokemonPokemonIDRoute;
  PublicPokemonIndexRoute: typeof PublicPokemonIndexRoute;
}

const PublicPokemonRouteRouteChildren: PublicPokemonRouteRouteChildren = {
  PublicPokemonPokemonIDRoute: PublicPokemonPokemonIDRoute,
  PublicPokemonIndexRoute: PublicPokemonIndexRoute,
};

const PublicPokemonRouteRouteWithChildren =
  PublicPokemonRouteRoute._addFileChildren(PublicPokemonRouteRouteChildren);

interface PublicRouteRouteChildren {
  PublicPokemonRouteRoute: typeof PublicPokemonRouteRouteWithChildren;
  PublicAboutRoute: typeof PublicAboutRoute;
  PublicIndexRoute: typeof PublicIndexRoute;
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicPokemonRouteRoute: PublicPokemonRouteRouteWithChildren,
  PublicAboutRoute: PublicAboutRoute,
  PublicIndexRoute: PublicIndexRoute,
};

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
);

export interface FileRoutesByFullPath {
  '': typeof PublicRouteRouteWithChildren;
  '/pokemon': typeof PublicPokemonRouteRouteWithChildren;
  '/about': typeof PublicAboutRoute;
  '/': typeof PublicIndexRoute;
  '/pokemon/$pokemonID': typeof PublicPokemonPokemonIDRoute;
  '/pokemon/': typeof PublicPokemonIndexRoute;
}

export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute;
  '/': typeof PublicIndexRoute;
  '/pokemon/$pokemonID': typeof PublicPokemonPokemonIDRoute;
  '/pokemon': typeof PublicPokemonIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/_public': typeof PublicRouteRouteWithChildren;
  '/_public/pokemon': typeof PublicPokemonRouteRouteWithChildren;
  '/_public/about': typeof PublicAboutRoute;
  '/_public/': typeof PublicIndexRoute;
  '/_public/pokemon/$pokemonID': typeof PublicPokemonPokemonIDRoute;
  '/_public/pokemon/': typeof PublicPokemonIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | ''
    | '/pokemon'
    | '/about'
    | '/'
    | '/pokemon/$pokemonID'
    | '/pokemon/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/about' | '/' | '/pokemon/$pokemonID' | '/pokemon';
  id:
    | '__root__'
    | '/_public'
    | '/_public/pokemon'
    | '/_public/about'
    | '/_public/'
    | '/_public/pokemon/$pokemonID'
    | '/_public/pokemon/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_public"
      ]
    },
    "/_public": {
      "filePath": "_public/route.tsx",
      "children": [
        "/_public/pokemon",
        "/_public/about",
        "/_public/"
      ]
    },
    "/_public/pokemon": {
      "filePath": "_public/pokemon/route.tsx",
      "parent": "/_public",
      "children": [
        "/_public/pokemon/$pokemonID",
        "/_public/pokemon/"
      ]
    },
    "/_public/about": {
      "filePath": "_public/about.tsx",
      "parent": "/_public"
    },
    "/_public/": {
      "filePath": "_public/index.tsx",
      "parent": "/_public"
    },
    "/_public/pokemon/$pokemonID": {
      "filePath": "_public/pokemon/$pokemonID.tsx",
      "parent": "/_public/pokemon"
    },
    "/_public/pokemon/": {
      "filePath": "_public/pokemon/index.tsx",
      "parent": "/_public/pokemon"
    }
  }
}
ROUTE_MANIFEST_END */
